from tkinter import *
from PIL import Image,ImageTk
img_root = Tk()
img_root.geometry("400x533")
image = Image.open("hartik.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()

img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik2.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()

img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik3.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()

img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik4.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()

img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik5.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()

img_root = Tk()
img_root.geometry("500x700")
image = Image.open("hartik6.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()


img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik7.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()

img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik8.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()


img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik9.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()


img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik10.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()


img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik11.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()


img_root = Tk()
img_root.geometry("500x667")
image = Image.open("hartik12.jpg")
photo = ImageTk.PhotoImage(image)
image_label = Label(image = photo)
image_label.pack() 
img_root.mainloop()
